name: HTTP Request Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest
    env:
      REPOS: "react,pandas"
      OWNERS: "facebook,pandas-dev"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python .github/scripts/get-stats.py ${{ env.REPOS }} ${{ env.OWNERS }}
        env:
          YOUR_TOKEN: ${{ secrets.GHPAT }}